title: Dev docs
description: Dev docs made with Jeykll using the Just the Docs theme.
url: https://docs-switzerlandomics.github.io
# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs
# remote_theme: hydecorp/hydejack@v9 logo: "/assets/images/pipedev_logo_1.png"
# ![Pipe Dev logo](/assets/images/pipedev_logo_1.png "logo")


aux_links:
  Github: https://github.com/docs-switzerlandomics.github.io
  SwitzerlandOmics.ch: https://switzerlandomics.ch

callouts:
  warning:
    title: Warning
    color: red

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

# add mathjax to all pages
# math: mathjax
